[base]
name = "Fool Engine"
# $HOME/Pictures/$name/$capture_path
capture_path = "screenshots"
# $HOME/Document/$name/$save_path
save_path = "saves"
# $exe_path/$assets_path
# $exe_path/$assets_path/assets.pak
assets_path = "assets"
fps = 60

[window]
defailt_size = { width = 800.0, height = 800.0 }
min_size = { width = 800.0, height = 800.0 }
max_size = { width = 1920.0, height = 1080.0 }
# position = { x = 100.0, y = 100.0 }
resizable = true
enabled_buttons = ["close", "maximize", "minimize"]
title = "Fool engine"
maximized = false
visible = true
transparent = false
blur = false
decorations = true
window_icon = "assets/image/linux.png"
preferred_theme = "Dark"
resize_increments = { width = 10.0, height = 10.0 }
content_protected = false
window_level = "Normal"
active = true
cursor = "assets/image/cursor.png"
fullscreen = false
